# Using NumPy for Linear Algebra Operations

Now that we know how to use NumPy arrays to create vectors and matrices, we can learn how to perform various linear algebra operations using Python.

To multiply a vector or matrix by a scalar, we use inbuilt Python multiplication between the NumPy array and the scalar:

```python
A = np.array([[1,2],[3,4]])
4 * A
```

Written out mathematically, this is:

$$
4 \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}= \begin{bmatrix} 4 & 8 \\ 12 & 16 \end{bmatrix}
$$

Therefore, our output in Python is:

```
[[ 4  8]
 [12 16]]
```

To add equally sized vectors or matrices, we can again use inbuilt Python addition between the NumPy arrays.

```python
A = np.array([[1,2],[3,4]])
B = np.array([[-4,-3],[-2,-1]])
A + B
```

Written out mathematically, this is:

$$
\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}+ \begin{bmatrix} -4 & -3 \\ -2 & -1 \end{bmatrix}= \begin{bmatrix} -3 & -1 \\ 1 & 3 \end{bmatrix}
$$

Therefore, our output in Python is:

```
[[ -3 -1]
 [1 3]]
```

Vector dot products can be computed using the `np.dot()` function:

```python
v = np.array([-1,-2,-3])
u = np.array([2,2,2])
np.dot(v,u)
```

Written out mathematically, this is:

$$
\begin{bmatrix} -1 \\ -2\\ -3 \\ \end{bmatrix}\cdot \begin{bmatrix} 2 \\ 2 \\ 2 \end{bmatrix} = -12
$$

Therefore, our output in Python is:

```
-12
```

Matrix multiplication is computed using either the `np.matmul()` function or using the `@` symbol as shorthand. It is important to note that using the typical Python multiplication symbol `*` will result in an elementwise multiplication instead.

```python
A = np.array([[1,2],[3,4]])
B = np.array([[-4,-3],[-2,-1]])
 
# one way to matrix multiply
np.matmul(A,B)
# another way to matrix multiply
A@B
```

Written out mathematically, this is:

$$
\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}\cdot \begin{bmatrix} -4 & -3 \\ -2 & -1 \end{bmatrix}= \begin{bmatrix} -8 & -5 \\ -20 & -13 \end{bmatrix}
$$

Therefore, our Python output is:

```
[[ -8  -5]
 [-20 -13]]
```



## Instructions

1. In script.py, we are given three matrices.

    Calculate the following equation using NumPy:

    $$
    D = 4A - 2B
    $$

    Save your equation to a variable called `D` and print it in the output terminal. Try calculating by hand before or after using Python to verify you understand how the operation works!

    <details>
        <summary>Stuck? Get a hint</summary>
    
    Let’s say we have the following NumPy arrays representing matrices:

    ```python
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[0, 2], [4, 6]])
    ```

    To calculate the equation:

    $$
    C = 8A + 6B
    $$

    We do the following in Python:

    ```python
    C = 8*A + 6*B
    ```
    </details>

2. Calculate the following matrix multiplication equation using NumPy:

    $$
    E = AC
    $$

    Save your equation to a variable called `E` and print it in the output terminal. Try calculating by hand before or after using Python to verify you understand how the operation works!

    What is the shape of our resulting matrix? Why is this?

    <details>
        <summary>Stuck? Get a hint</summary>
    
    Let’s say we have the following NumPy arrays representing matrices:

    ```python
    A = np.array([[1, 2, 3], [4, 5, 6]])
    B = np.array([[0, 2], [4, 6], [3, 2]])
    ```

    To calculate the equation:

    $$
    C = AB
    $$

    We have two methods to do this in Python. One method is:

    ```python
    C = A@B
    ```

    The second method is:

    ```python
    C = np.matmul(A, B)
    ```

    The resulting matrix is 2x2 because matrix A has two rows and matrix B has two columns.
    </details>

3. Calculate the following matrix multiplication equation using NumPy:

    $$
    F = CA
    $$

    Save your equation to a variable called `F` and print it in the output terminal. Try calculating by hand before or after using Python to verify you understand how the operation works!

    What is the shape of our resulting matrix? Is the shape of matrix `F` different from the shape of matrix `E`? Why is this?

    <details>
        <summary>Stuck? Get a hint</summary>
    
    This time the resulting matrix is 3x3 because matrix C has three rows and matrix B has three columns.
    </details>


In [ ]:
import numpy as np

# Given
# 2 x 3 matrix
A = np.array([[2,3,-4], [-2, 1, -3]])
# 2 x 3 matrix
B = np.array([[1,-1,4], [3,-3,3]])
# 3 x 2 matrix
C = np.array([[1, 2], [3, 4], [5, 6]])

# Calculate D = 4A - 2B


# Calculate E = AC


# Calculate F = CA



### Solution

In [1]:
import numpy as np

# Given
# 2 x 3 matrix
A = np.array([[2,3,-4], [-2, 1, -3]])
# 2 x 3 matrix
B = np.array([[1,-1,4], [3,-3,3]])
# 3 x 2 matrix
C = np.array([[1, 2], [3, 4], [5, 6]])

# Calculate D = 4A - 2B
D = 4 * A - 2 * B
print(D)

# Calculate E = AC
E = A@C
print(E)

# Calculate F = CA
F = C@A
print(F)

[[  6  14 -24]
 [-14  10 -18]]
[[ -9  -8]
 [-14 -18]]
[[ -2   5 -10]
 [ -2  13 -24]
 [ -2  21 -38]]
